name: LifeStealDuels
version: '${version}'

main: Vaelior.lifeStealDuels.LifeStealDuels
api-version: '1.21'
commands:
  lskit:
    description: opens LifeSteal duels kit selection menu
    usage: /<command>
  lsgetmaps:
    description: opens list of worlds (op members only)
    usage: /<command>
  lstelemap:
    description: teleports player to map
    usage: /<command> mapName
  lscreatemap:
    description: creates map with name
    usage: /<command> mapName
